#!/usr/bin/env bash

# Function to display information about a subdomain
display_info() {
    sub_domain=$1
    record_type=$(dig +short -t A "$sub_domain.$domain" | awk '{ if(NF==0) print "CNAME"; else print "A" }')
    destination=$(dig +short "$sub_domain.$domain" | awk 'NR==1{print}')
    echo "The subdomain $sub_domain is a $record_type record and points to $destination"
}

# Domain to audit
domain="$1"

# Subdomain to audit (optional)
sub_domain="$2"

# If sub_domain is not provided, audit default subdomains
if [ -z "$sub_domain" ]; then
    sub_domains=("www" "lb-01" "web-01" "web-02")
else
    sub_domains=("$sub_domain")
fi

# Loop through subdomains and display information
for sub in "${sub_domains[@]}"; do
    display_info "$sub"
done
