#!/usr/bin/env bash
# Configure your domain zone so that the subdomain www points to your load-balancer IP

# Function to display information about a subdomain
display_info() {
    local sub_domain="$1"
    local full_domain="$sub_domain.$domain"
    local answer_section
    answer_section=$(dig +short "$full_domain" | awk 'NR==1{print}')

    if [[ -z "$answer_section" ]]; then
        echo "No DNS records found for $full_domain"
    else
        echo "The subdomain $sub_domain is a A record and points to $answer_section"
    fi
}

# Domain to audit
domain="$1"

# Check if domain is provided
if [[ -z "$domain" ]]; then
    echo "Usage: $0 <domain> [sub_domain]"
    exit 1
fi

# Subdomain to audit (optional)
sub_domain="$2"

# If sub_domain is not provided, audit default subdomains
if [[ -z "$sub_domain" ]]; then
    sub_domains=("www" "lb-01" "web-01" "web-02")
else
    sub_domains=("$sub_domain")
fi

# Loop through subdomains and display information
for sub in "${sub_domains[@]}"; do
    display_info "$sub"
done
