#!/usr/bin/env bash
# script that transfers a file from our client to a server
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Extract parameters
PATH_TO_FILE=$1
IP=$2
USERNAME=$3
SSH_KEY=$4

# Disable strict host key checking for scp
SCP_OPTIONS="-o StrictHostKeyChecking=no"

# Transfer the file using scp
scp $SCP_OPTIONS -i "$SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP":~/ 

# Check if scp command was successful
if [ $? -eq 0 ]; then
    echo "File transferred successfully."
else
    echo "File transfer failed."
fi
