#!/usr/bin/env bash
# script that installs Nginx if not already installed

set -euo pipefail

# Install Nginx if not already installed
if ! command -v nginx &>/dev/null; then
    echo "Installing Nginx..."
    sudo apt update
    sudo apt install -y nginx
fi

# configures Nginx to listen on port 80 and respond with "Hello World!"
sudo tee /etc/nginx/sites-available/default >/dev/null <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        echo "Hello World!";
    }
}
EOF

# restarts Nginx without using systemctl
if pgrep -x "nginx" >/dev/null; then
	sudo kill -s HUP $(pgrep -x "nginx")
	echo "Nginx restarted."
else
	echo "Nginx is not running. No need to restart."
fi
