#!/usr/bin/env bash
# Installs and configures HAproxy
set -euo pipefail

# Install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
sudo tee /etc/haproxy/haproxy.cfg >/dev/null <<EOF
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000ms
    timeout client  50000ms
    timeout server  50000ms

frontend http_front
    bind *:80
    # Restrict access to HAProxy stats page
    acl localhost src 127.0.0.1
    acl localnet src 192.168.0.0/16
    acl localnet src fc00::/7
    acl localnet src fe80::/10
    acl trusted_ips src 10.0.0.0/8 172.16.0.0/12
    http-request allow if localhost
    http-request allow if localnet
    http-request allow if trusted_ips
    http-request deny
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 34.203.201.29:80 check
    server web-02 54.160.91.89:80 check
EOF

# Enable and start HAProxy service
sudo systemctl enable haproxy
sudo systemctl restart haproxy

# Test the load balancer functionality
echo "Testing load balancer functionality..."
echo "Expecting response from web-01:"
curl -Is 52.201.221.182 | grep -i "X-Served-By"
echo "Expecting response from web-02:"
curl -Is 52.201.221.182 | grep -i "X-Served-By"
