#!/usr/bin/env bash

nginx -t && systemctl start nginx
if ! sudo netstat -tuln | grep ':80\s'; then sudo tee /etc/nginx/sites-available/default > /dev/null << EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF
fi
sudo systemctl reload nginx
