#!/usr/bin/env bash
# listens on port 98 on localhost
import socket
HOST = '127.0.0.1'
PORT = 98
# Create a TCP/IP socket
with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
s.bind((HOST, PORT))
s.listen()
