#!/usr/bin/env bash
# command(s) used to fix the issue

docker build -t holbertonschool/265-0

# Runs the Docker container, mapping port 8080 on the host to port 80 in the container
docker run -p 8080:80 -d holbertonschool/265-0
